# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n8CykW1g7KQSWr4JLUlK_wD7O7E2ytoQ
"""

import pandas as pd
s=pd.Series([10,20,30,40,50])
print(s)